project:
  type: website

website:
  title: "Mut Piña, Antoni (PhD)"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: styles.scss
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
